### ISSUE TITLE
when created a new branches, it always failed with this

### ISSUE THREAD

**Issue by ltDino** [shimewtr/submit_pull_request#39]
```
Traceback (most recent call last):
Branch name is incorrect
  File "/submit_pull_request.py", line 126, in parse_branch_id
    branch_id = int(m[-1][1:])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/submit_pull_request.py", line 149, in <module>
    SubmitPullRequest()
  File "/submit_pull_request.py", line 26, in __init__
    self.branch_id = self.parse_branch_id()
  File "/submit_pull_request.py", line 129, in parse_branch_id
    self.error_handler("Branch name is incorrect")
  File "/submit_pull_request.py", line 80, in error_handler
    raise Exception
Exception
```

**Comment by shimewtr** [comment]
@ltDino 

The name of the branch must contain the ID of the issue, as described in the README.
Do you get the same error if you use a branch name like the one described here?
https://github.com/shimewtr/submit_pull_request#branch
