### ISSUE TITLE
Failed to create pull request

### ISSUE THREAD

**Issue by ArthurKun21** [shimewtr/submit_pull_request#40]
```
Traceback (most recent call last):
  File "/submit_pull_request.py", line 73, in create_pull_request
    draft=DRAFT)
  File "/usr/local/lib/python3.7/site-packages/github/Repository.py", line 1348, in create_pull
    return self.__create_pull_1(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/github/Repository.py", line 1380, in __create_pull_1
    title=title, body=body, base=base, head=head, draft=draft
  File "/usr/local/lib/python3.7/site-packages/github/Repository.py", line 1393, in __create_pull
    "POST", f"{self.url}/pulls", input=post_parameters
  File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 355, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 422 {"message": "Validation Failed", "errors": [{"resource": "PullRequest", "code": "custom", "message": "No commits between master and 11-setup-the-new-issue-and-test-the-pull-request-again"}], "documentation_url": "https://docs.github.com/rest/reference/pulls#create-a-pull-request"}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/submit_pull_request.py", line 149, in <module>
    SubmitPullRequest()
  File "/submit_pull_request.py", line 30, in __init__
    self.pr = self.create_pull_request()
  File "/submit_pull_request.py", line 76, in create_pull_request
    self.error_handler("Failed to create pull request")
  File "/submit_pull_request.py", line 80, in error_handler
    raise Exception
Exception
```

name of the issue
`setup the new issue and test the pull request again` and it was an issue number 11

created a new branch inside the issue
![image](https://user-images.githubusercontent.com/16458204/160969544-649a8977-2219-453c-b2c2-43aa1de56f58.png)

create a new branch name `11-setup-the-new-issue-and-test-the-pull-request-again`

Manually rerun the job will create the pull request from the issue

**Comment by ArthurKun21** [comment]
Sorry

turns out adding this
`on: ["push"]`

solved issue
